"use client";
import { useState, useEffect } from "react";
import Image from "next/image";
import Logo from "./bfg-logo.png";
import Animation from "../../public/office_banner.jpg";

export default function Main() {
  

  return (
    <>
      <div className="">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet justo donec enim diam vulputate ut pharetra sit. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Suscipit adipiscing bibendum est ultricies integer. Ultricies mi eget mauris pharetra et ultrices neque ornare aenean. Est placerat in egestas erat imperdiet sed euismod nisi. Aenean euismod elementum nisi quis eleifend quam. Sit amet mauris commodo quis imperdiet massa tincidunt. Erat pellentesque adipiscing commodo elit. Eros donec ac odio tempor orci dapibus ultrices in. Massa id neque aliquam vestibulum morbi blandit cursus risus. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.

Libero justo laoreet sit amet. Ultricies mi quis hendrerit dolor magna eget. Est ante in nibh mauris cursus mattis molestie a. In ornare quam viverra orci sagittis eu volutpat odio. Risus nullam eget felis eget nunc lobortis mattis aliquam faucibus. Sit amet purus gravida quis blandit turpis cursus in. Arcu ac tortor dignissim convallis aenean et tortor. Fermentum dui faucibus in ornare quam viverra orci sagittis. Nulla facilisi cras fermentum odio eu feugiat. Eu feugiat pretium nibh ipsum consequat nisl. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Tristique nulla aliquet enim tortor. Bibendum neque egestas congue quisque egestas diam in. Vitae congue eu consequat ac felis donec et. Arcu bibendum at varius vel. Tristique nulla aliquet enim tortor at auctor. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies.

Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Tempor orci eu lobortis elementum nibh tellus. Nulla at volutpat diam ut. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Ultricies tristique nulla aliquet enim tortor at. Faucibus nisl tincidunt eget nullam non. Pellentesque dignissim enim sit amet venenatis. Aliquet nibh praesent tristique magna sit amet. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Ipsum dolor sit amet consectetur adipiscing elit duis. At consectetur lorem donec massa sapien faucibus et molestie.

A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Placerat in egestas erat imperdiet sed euismod nisi porta. Sem et tortor consequat id porta nibh. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Felis eget nunc lobortis mattis. Sapien eget mi proin sed libero enim sed. Integer feugiat scelerisque varius morbi enim nunc. Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet. Odio tempor orci dapibus ultrices in. Pellentesque habitant morbi tristique senectus et netus. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Bibendum arcu vitae elementum curabitur vitae nunc sed velit dignissim. Ullamcorper malesuada proin libero nunc consequat interdum varius. Elit ut aliquam purus sit amet luctus venenatis lectus. Magna etiam tempor orci eu lobortis. Viverra ipsum nunc aliquet bibendum enim facilisis.

Pharetra massa massa ultricies mi quis. Scelerisque mauris pellentesque pulvinar pellentesque. Velit scelerisque in dictum non consectetur a erat nam. Posuere urna nec tincidunt praesent. Eu scelerisque felis imperdiet proin fermentum. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Sit amet aliquam id diam maecenas ultricies mi. Diam sit amet nisl suscipit adipiscing bibendum est ultricies. Malesuada bibendum arcu vitae elementum curabitur vitae nunc. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Eu turpis egestas pretium aenean.

Phasellus faucibus scelerisque eleifend donec pretium vulputate. Vitae tortor condimentum lacinia quis. In vitae turpis massa sed elementum. Elementum sagittis vitae et leo duis. Netus et malesuada fames ac turpis egestas integer eget aliquet. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Dictum sit amet justo donec. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Ante metus dictum at tempor commodo ullamcorper a lacus. Lectus vestibulum mattis ullamcorper velit.

Volutpat ac tincidunt vitae semper quis. Phasellus vestibulum lorem sed risus ultricies tristique nulla. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Non sodales neque sodales ut etiam sit. Amet cursus sit amet dictum sit amet. Fringilla ut morbi tincidunt augue interdum velit euismod. Placerat duis ultricies lacus sed turpis tincidunt. Duis tristique sollicitudin nibh sit amet. Ut consequat semper viverra nam. Blandit turpis cursus in hac habitasse platea dictumst. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Turpis nunc eget lorem dolor sed viverra ipsum. Id consectetur purus ut faucibus pulvinar. Laoreet id donec ultrices tincidunt arcu non. Gravida arcu ac tortor dignissim. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Pharetra diam sit amet nisl suscipit adipiscing bibendum est.

Augue mauris augue neque gravida in fermentum et. Leo duis ut diam quam nulla porttitor massa. Tincidunt id aliquet risus feugiat in ante metus dictum at. Turpis egestas sed tempus urna et. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper. In dictum non consectetur a. Vivamus at augue eget arcu dictum varius duis. At elementum eu facilisis sed odio. Quis risus sed vulputate odio. Pellentesque habitant morbi tristique senectus et. Adipiscing vitae proin sagittis nisl rhoncus mattis. Orci nulla pellentesque dignissim enim sit amet venenatis. Nibh mauris cursus mattis molestie.

In fermentum posuere urna nec. Proin sed libero enim sed faucibus. Odio pellentesque diam volutpat commodo sed egestas egestas. Felis donec et odio pellentesque diam volutpat. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Vel risus commodo viverra maecenas. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Nec feugiat in fermentum posuere urna nec. Tellus integer feugiat scelerisque varius. Volutpat blandit aliquam etiam erat velit scelerisque in. Nunc congue nisi vitae suscipit tellus mauris a diam maecenas. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Libero enim sed faucibus turpis in eu mi bibendum neque.

Iaculis urna id volutpat lacus laoreet. Amet volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Egestas sed tempus urna et pharetra pharetra massa. Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Dui faucibus in ornare quam. Ut etiam sit amet nisl purus in mollis nunc sed. Tincidunt lobortis feugiat vivamus at augue. Pellentesque id nibh tortor id aliquet lectus proin nibh. Sem integer vitae justo eget magna fermentum iaculis eu. Elementum nisi quis eleifend quam adipiscing vitae proin. Justo donec enim diam vulputate ut pharetra sit amet. Et tortor at risus viverra adipiscing at in tellus integer. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Quam id leo in vitae turpis massa sed elementum tempus. Sed euismod nisi porta lorem mollis aliquam ut.

Nisi est sit amet facilisis magna etiam tempor orci. Vitae ultricies leo integer malesuada nunc vel. Quam pellentesque nec nam aliquam sem et tortor. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Felis donec et odio pellentesque diam volutpat commodo. Varius duis at consectetur lorem. Feugiat scelerisque varius morbi enim nunc faucibus. Mattis enim ut tellus elementum sagittis. Egestas maecenas pharetra convallis posuere. Elit sed vulputate mi sit amet mauris commodo. Aliquam sem fringilla ut morbi tincidunt augue interdum. Est ultricies integer quis auctor elit sed vulputate. Tempus quam pellentesque nec nam aliquam sem et tortor. Lectus quam id leo in vitae turpis massa sed elementum. Morbi leo urna molestie at elementum eu.

Ipsum a arcu cursus vitae congue. Mi in nulla posuere sollicitudin aliquam. Ut consequat semper viverra nam libero justo laoreet. Hendrerit gravida rutrum quisque non tellus orci. Ut venenatis tellus in metus vulputate. Eu consequat ac felis donec et odio pellentesque diam. Consectetur purus ut faucibus pulvinar. Urna et pharetra pharetra massa massa ultricies. Pellentesque habitant morbi tristique senectus et netus et. Ipsum consequat nisl vel pretium lectus quam id leo. At urna condimentum mattis pellentesque id. Arcu risus quis varius quam quisque id diam vel quam. Iaculis urna id volutpat lacus. Vel fringilla est ullamcorper eget nulla facilisi. Enim eu turpis egestas pretium aenean pharetra. Malesuada proin libero nunc consequat interdum. Sit amet cursus sit amet dictum sit amet. Fusce ut placerat orci nulla pellentesque dignissim.

Lectus mauris ultrices eros in cursus turpis. Eget egestas purus viverra accumsan in nisl nisi scelerisque. Nunc id cursus metus aliquam eleifend mi. In massa tempor nec feugiat nisl pretium fusce id velit. Enim sed faucibus turpis in eu mi. Tristique risus nec feugiat in fermentum posuere urna nec. Nunc sed augue lacus viverra vitae congue. Semper viverra nam libero justo. Semper eget duis at tellus at. Vivamus at augue eget arcu dictum varius duis at consectetur. Massa tincidunt dui ut ornare lectus sit amet. Amet tellus cras adipiscing enim eu. Arcu cursus vitae congue mauris. Amet purus gravida quis blandit turpis. Facilisis magna etiam tempor orci eu. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. At lectus urna duis convallis convallis tellus. Sollicitudin aliquam ultrices sagittis orci a scelerisque.

      </div>
    </>
  );
}
